networks:
  todo-network:

services:
  todo-api:
    build: 
      context: ./rocket-todo-api
      dockerfile: todo-api.dockerfile
    image: todo-api:puvs
    container_name: todo-api
    ports:
      - "8000:8000"
    networks:
      - todo-network

  todo-web:
    build: 
      context: ./yew-todo-web
      dockerfile: todo-web.dockerfile
    image: todo-web:puvs
    container_name: todo-web
    ports:
      - "8080:8080"
    networks:
      - todo-network
    depends_on:
      - todo-api