networks:
  todo-network:

services:
  todo-db:
    image: mongo:latest
    container_name: todo-db
    ports:
      - "27017:27017"
    networks:
      - todo-network

  todo-api:
    build: 
      context: ./rocket-todo-api
      dockerfile: todo-api.dockerfile
    #image: disgame/lab:todo-api
    container_name: todo-api
    ports:
      - "8000:8000"
    networks:
      - todo-network
    depends_on:
      - todo-db

#  todo-web:
#    build: 
#      context: ./yew-todo-web
#      dockerfile: todo-web.dockerfile
#    image: todo-web:puvs
#    container_name: todo-web
#    ports:
#      - "8080:8080"
#    networks:
#      - todo-network
#    depends_on:  
#      - todo-api

  todoui-thymeleaf:
    #image: maeddes/todoui-thymeleaf:v2404
    image: disgame/lab:todo-web
    build:
      context: ./sample/otel-in-action/todoui-thymeleaf
      dockerfile: Dockerfile
    networks:
      - todo-network
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://todo-api:8000
    depends_on:
      - todo-api