apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: todo-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: todo-api
status:
  loadBalancer: {}
