apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-web
  name: todo-web
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: todo-web
status:
  loadBalancer: {}
